name: Javascript CI
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        type: choice
        options:
          - 20.x
          - 22.x
          - 24.x
          - 25.x
        default: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ inputs.node-version }}
          repository: ${{ github.repository }}
          # cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      - name: Run tests
        run: npm test
 